### ISSUE TITLE
One modification and one question about Jet

### ISSUE THREAD

**Issue by xinbaili** [eic/sidis-eic#160]
Hi All, I think I may find a mistake in `src/AnalysisAthena.cxx` , line 88-91. It should be
`while(nevt<maxEvents){...` and move `tr.Next()` to the end of the event loop, the original code iterates event from 1 to maxEvents while I think it should be 0 to maxEvents-1.
And one question is that I see there are some fastjet objects in dd4hep analysis, (though I don't find the cite .h file or corresponding lib, a little unclear) I wonder that has the Jet reconstruction finely implemented in Full detector simulation output analysis? I know it has been set in Delphes.
It is the first time I pull an issue to github, is here the place I should put things like this? Any feedback is welcome.

**Comment by c-dilks** [comment]
Thanks, I'll take a look at the `AnalysisAthena` issue.

We use standard Github workflow, issues and pull requests, so this is the correct place for reporting bugs, requesting new features, etc. Note that I plan to migrate us to the [EIC organization](https://github.com/eic), which will make contributing much easier; it's better to wait until then before opening any pull requests. This will take a few more days, but for now I recommend joining the [EIC organization](https://github.com/eic), and also join the [EPIC devs team](https://github.com/orgs/eic/teams/epic-devs). 

As for jets, currently only the fast simulation `AnalysisDelphes` reads jets; `AnalysisAthena` does not, and since we plan to have `AnalysisEpic` for the future, it's not really worth adding to `AnalysisAthena` (other than for prototyping for `AnalysisEpic`, since the data model will be somewhat similar). It's possible the jets implementation in `AnalysisDelphes` is broken, since it has not been tested for a while. Would you be interested in working on getting jets working in this framework?

**Comment by xinbaili** [comment]
Hi Christopher, though it sounds really interesting and I would like to try, I haven't done work related to Jet. So I need to get started with fastjet first, to be familiar with it, to compare and understand the jet reco implemented here and test it and give a look at results. It might be a little long time, (or may be soon if I find it is easy for me to understand). I think if you are finding someone professional in jet reco., I will recommend you Nicolas who has the experience of these things in ecce afterburner code. Of course if time allows, and I get familiar with it quickly, I am willing to join.

**Comment by c-dilks** [comment]
Hi @xinbaili, can you review the proposed changes in #167 to see if it's correct? Setting `maxEvents` to 10 and printing `tr.GetCurrentEntry()` for each event now returns
```
0 events...
1 events...
2 events...
3 events...
4 events...
5 events...
6 events...
7 events...
8 events...
9 events...
```
which I believe is the correct behavior. Previously event 0 was indeed being skipped.

**Comment by xinbaili** [comment]
Hi @c-dilks, Now it's correct. You could merge it to the master.
